# Generated by Django 5.1.4 on 2025-01-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CAR_RESERVATION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Select_your_car', models.CharField(blank=True, max_length=200)),
                ('Pick_up_City', models.CharField(blank=True, max_length=200)),
                ('Drop_off_City', models.CharField(blank=True, max_length=200, null=True)),
                ('Pick_up_DateTime', models.DateTimeField(blank=True)),
                ('Drop_off_DateTime', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Send_Your_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200)),
                ('Email', models.EmailField(blank=True, max_length=200)),
                ('Phone', models.IntegerField()),
                ('Project', models.CharField(blank=True, max_length=200)),
                ('Subject', models.CharField(blank=True, max_length=200)),
                ('Massage', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
